name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Atualizado para usar Node.js 16

      - name: Generate snake game output
        run: |
          git clone https://github.com/Platane/snk.git
          cd snk
          npm install
          npm run build
          cp dist/index.html ../../snake-output.html

      - name: Push snake output to the repository
        run: |
          git config --local feliciano.rodrigues16062012 "actions@github.com"
          git config --local Feliciano-Rodrigues "GitHub Actions"
          git add ../../snake-output.html
          git commit -m "Add snake output"
          git push
