name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate the snake GIF
        run: node generate_snake_gif.js

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local Feliciano-Rodrigues "GitHub Actions"
          git add github-contribution-grid-snake.gif
          git commit -m "Generated snake animation GIF"
          git push
