name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clone the snake repository
        run: git clone https://github.com/Platane/snk.git

      - name: Generate the snake grid with contributions
        run: |
          cd snk
          npm install
          npm run generate --output ../github-contribution-grid-snake.svg --user Feliciano-Rodrigues

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ../github-contribution-grid-snake.svg
          git commit -m "Generated snake animation grid"
          git push
